### ISSUE TITLE
please help me,CUDNN_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by ztttkx0804** [andreasveit/densenet-pytorch#6]
Hey Andreas,

when I run your code,RuntimeError: CUDNN_STATUS_ARCH_MISMATCH,why?
Thanks!

**Comment by andreasveit** [comment]
Can you please provide more details. The erro does not look like a problem with this repo.

**Comment by ztttkx0804** [comment]
I use the same code as you,in the process of reproduction,emerging RuntimeError: CUDNN_STATUS_ARCH_MISMATCH,but when i run classical or simple resnet,process finished with exit `code0.
`Traceback (most recent call last):
  File "/tmp/pycharm_project_505/train.py", line 238, in <module>
    main()
  File "/tmp/pycharm_project_505/train.py", line 103, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "/tmp/pycharm_project_505/train.py", line 126, in train
    output = model(input_var)
  File "/home/zw/ztpytorch/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/tmp/pycharm_project_505/densenet.py", line 111, in forward
    out=self.conv1(x)
  File "/home/zw/ztpytorch/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zw/ztpytorch/pytorch/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/home/zw/ztpytorch/pytorch/lib/python3.5/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_ARCH_MISMATCH

Process finished with exit code 1`
